# Generated by Django 3.2.9 on 2021-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_cover',
            field=models.ImageField(blank=True, upload_to='listing/'),
        ),
    ]
